Construct staff graph, return teams
piloza/email-classification-challenge pull request #29
Opened 2017-02-27 16:27 UTC by pdubreuil1

2017-02-27 17:34 UTC, louismartin reviewed
C'est bon pour moi apres prise en compte eventuelle de mes commentairs :)

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +        G.add_node("sender")
Tu voulais pas faire `G.add_node(sender)`plutot ?

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +    if print(nx.is_connected(G)) is False:
Il sert à quoi le print ?
En général plutot que de mettre `if a is False:` on écrit `if not a:`

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +        G_connected = list_graph[0]
ça serait pas plus simple de faire `G_connected = next(nx.connected_component_subgraphs(G))` (pas besoin de deplier tout le générateur)

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +    dict = {}
Faut éviter de nommer des variables avec des noms utilisés dans la librairie standard

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +    return dict
Ca serait pas plus clair de retourner `return n_clusters, values` plutôt qu'un dictionnaire ?

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +    n_clusters = len(counter_set)
Si j'ai bien compris, la tu veux juste avec le nombre de clés différentes dans ton dictionnaire ?
Ça marcherait de faire `n_clusters = len(values)`(égal au nombre de clés du dictionnaire values).
Si oui ya pas forcement besoin de retourner n_clusters du coup vu qu'on peut le calculer facilement à partir de values.

2017-02-27 17:34 UTC, louismartin commented on tools/staff_graph.py
> +            - n_clusters: number of clusters in the Louvain assignment
Si on a bien `n_clusters = len(values)` on peut retirer l'argument n_clusters

2017-02-27 17:38 UTC, pdubreuil1 commented on tools/staff_graph.py
> +        G.add_node("sender")
si

2017-02-27 17:38 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    if print(nx.is_connected(G)) is False:
c'est pep8 qui m'a dit d'écrire ça mais je vais changer du coup. Le print c'est une type.

2017-02-27 17:39 UTC, pdubreuil1 commented on tools/staff_graph.py
> +        G_connected = list_graph[0]
il n'y a que 3 sous graphs dans tous les cas et la je sais que ça marche

2017-02-27 17:40 UTC, louismartin commented on tools/staff_graph.py
> +    if print(nx.is_connected(G)) is False:
Ah bah si PEP8 me contredit, c'est lui qui a raison !

2017-02-27 17:41 UTC, louismartin commented on tools/staff_graph.py
> +        G_connected = list_graph[0]
Ok fair enough, après c'est aussi plus joli et compact :)

2017-02-27 17:42 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    n_clusters = len(counter_set)
il y a autant de clef que de noeuds (~9870) ici je veux le nombre de valeurs différentes. (il me semble que c'est qd même faux, je vais arranger ça)

2017-02-27 17:42 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    return dict
OK pour le nom de variable.
je pensais que c'était une best pratice mais oui on peut changer l'output oui.

2017-02-27 17:42 UTC, pdubreuil1 commented on tools/staff_graph.py
> +            - n_clusters: number of clusters in the Louvain assignment
oui

2017-02-27 18:09 UTC, louismartin commented on tools/staff_graph.py
> +    n_clusters = len(counter_set)
Dans un dictionnaires les clés sont forcément différentes.
Pour convertir en set en une ligne et sans for loop tu peux faire `set(mon_objet)`

2017-03-09 09:09 UTC, zaccharieramzi commented on tools/staff_graph.py
> +    if print(nx.is_connected(G)) is False:
non non il faut bien mettre `if not a`

2017-03-09 09:16 UTC, zaccharieramzi requested changes
Pour moi y a des choses pas claires qu'il faut changer.

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +from matplotlib import pylab as pl
il faut essayer de mettre ses import dans l'ordre alphabétique

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +                G.add_node(str(rec))
pk `str(rec)` et pas `rec` ?

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +                G.add_edge(sender, str(rec), weight=1/len(recipients_list))
idem.

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +    values = {}
`values` n'est pas très parlant comme nom de variable

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +        output.add(counter_set)
je comprends pas du tout ce que tu fais dans cette boucle. Déjà la variable `output` sort de nulle part je vois pas comment ça marche, ensuite tu lui ajoutes n fois un set vide ...

2017-03-09 09:16 UTC, zaccharieramzi commented on tools/staff_graph.py
> +    return dict
Pour le coup plus chaud de retourner un dictionnaire en effet.

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +            - n_clusters: number of clusters in the Louvain assignment
non on ne l'a pas d coup je garde

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    return dict
je retourne un dictionnaire du nom `output_dict
`

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    dict = {}
done

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    n_clusters = len(counter_set)
je fais `n_clusters = len(set(teams.values()))`

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +        output.add(counter_set)
c'est enlevé. Aucun sens en effet.

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    values = {}
j'ai mis `teams`

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +        G_connected = list_graph[0]
j'ai mis ton truc pour te faire plaisir

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +    if print(nx.is_connected(G)) is False:
done

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +                G.add_edge(sender, str(rec), weight=1/len(recipients_list))
changed

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +                G.add_node(str(rec))
changed

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +        G.add_node("sender")
changed

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +from matplotlib import pylab as pl
putain je n'avais pas vu. Je change

2017-03-09 10:28 UTC, pdubreuil1 commented on tools/staff_graph.py
> +from matplotlib import pylab as pl
en fait c'était bien fait il me semble.

2017-03-09 12:06 UTC, zaccharieramzi approved these changes
Good for me

2017-03-09 12:06 UTC, zaccharieramzi commented on tools/staff_graph.py
> +            dictionary with to elements:
petite faute d'orthographe

2017-03-09 12:10 UTC, merged